### ISSUE TITLE
Change Request regarding /portal

### ISSUE THREAD

**Issue by MFrank2** [dc4eu/vc#55]
document_data object: delete object, of no use in a portal user interface - all relevant information shall be included in the attestation object

**Comment by masv3971** [comment]
What you mean is that /portal only should return `attestation`?

**Comment by MFrank2** [comment]
This point can of course still be discussed. Input from other parties can be helpful here. 
The intention of this endpoint in its pure form is that only all the information required for a superficial but nonetheless useful display in a user interface (e.g. portal) is returned. 
The specific content of the business document is not necessary for this purpose. We have devised the attestation object for this purpose, which contains all the display information.
There is currently no intention or plan to use the business information from the document_data object for this purpose, so in our opinion this is superfluous traffic.

**Comment by masv3971** [comment]
I can see your point in reducing the amount of unnecessary data to the portal.
Will leave this issue open some time to let others to share there opinion.

**Comment by MFrank2** [comment]
Agree
