### ISSUE TITLE
Overarching Change Requests 

### ISSUE THREAD

**Issue by MFrank2** [dc4eu/vc#58]
revocation object everywhere: Rename id to revocation_id (or without underscore..) to be clearly identifiable inside the database; id could be very misleading during selections

**Comment by masv3971** [comment]
My reasoning on this is, since we are using a document database, each attribute is located within a hierarchical structure (like json). "id" will not just be found in the database, it will be found with "revocation.id", does that make sense?

**Comment by MFrank2** [comment]
Thank you for the clarification. That makes sense and is fine.
