### ISSUE TITLE
docker-compose.yaml variables possible?

### ISSUE THREAD

**Issue by MFrank2** [dc4eu/vc#59]
Is it possible to set the FQDN of the images in a variable? Our server is not allowed to connect directly to the internet, we pull the containers via our jfrog artifactory. 

Example:
services:
  apigw:
    container_name: "vc_dev_apigw"
    image: **docker.sunet.se**/dc4eu/apigw:latest
    restart: always
    volumes:
      - ./dev_config_docker.yaml:/config.yaml:ro
      - /var/log/sunet:/var/log/sunet
    depends_on:
      - redis
      - mongo
    networks:
      vc-dev-net:
        ipv4_address: 172.16.50.2
    environment:
      - "VC_CONFIG_YAML=config.yaml"

The bold formatted "docker.sunet.se" would have to be in a variable that we have to set at startup. The same for redis/mongo/jaeger.

**Comment by masv3971** [comment]
As stated in the README file in this repo, this repo and its tools and scripts is intended for developers. However I have made this repo (https://github.com/dc4eu/vc_up_and_running) intended for running the code. 

I will update the README in this repo with this info and add url in variable in vc_up_and_running repo.

**Comment by MFrank2** [comment]
Seems fine
