### ISSUE TITLE
DELETE /document endpoint: No validation error when leaving out required parameters

### ISSUE THREAD

**Issue by JuAlMan** [dc4eu/vc#80]
Using image docker.sunet.se/dc4eu/apigw:apiv28

It is possible to execute the DELETE /document call with an empty request body.

As all three parameters (document_id, document_type, authentic_source) are required, leaving out any of them 
should yield a validation error.

**Comment by masv3971** [comment]
should be fixed, https://github.com/dc4eu/vc/commit/e1ea46f3d3bd5e1393e1686af6d9c465efd1d4ca

try docker tag apiv28
