### ISSUE TITLE
No request parameter validation in PUT /document/identity

### ISSUE THREAD

**Issue by JuAlMan** [dc4eu/vc#81]
Using image docker.sunet.se/dc4eu/apigw:apiv28

It is possible make a request like this without getting any validation errors:

```
{
    "identities": [
        {
            "schema": {
                "name": "DE",
                "version": "1.0.0"
            }
        }
    ]
}
```

Leaving out the identities-array results in an internal server error.

As all request parameters are required, a validation error should be returned when one or more parameter are missing.
See also issue #75 for validation of the identity-objects submitted in the array.

**Comment by masv3971** [comment]
should be fixed with, https://github.com/dc4eu/vc/commit/e1ea46f3d3bd5e1393e1686af6d9c465efd1d4ca
