### ISSUE TITLE
Missing request parameter validation in DELETE /document/identity

### ISSUE THREAD

**Issue by JuAlMan** [dc4eu/vc#82]
Using image docker.sunet.se/dc4eu/apigw:apiv28

In the current implementation there seems to be no request parameter validation, it is for example possible to submit an empty request object.

As all four parameters are required, a validation error should be returned if one or more parameters are missing.

**Comment by masv3971** [comment]
Should be fixed with, https://github.com/dc4eu/vc/commit/e1ea46f3d3bd5e1393e1686af6d9c465efd1d4ca
