### ISSUE TITLE
Identity-Mapping endpoint: Wrong path and missing request parameter validation

### ISSUE THREAD

**Issue by JuAlMan** [dc4eu/vc#84]
Using image docker.sunet.se/dc4eu/apigw:apiv28

There is a mismatch between the implementation and the spec regarding the path of the Identity-Mapping endpoint.
According to the spec the path is /identity/mapping.
In the current implementation it is /id/mapping.

Also there seems to be no validation of the request parameter as you can leave out both authentic_source and identity without getting a validation error.

**Comment by masv3971** [comment]
Validation is fixed with, https://github.com/dc4eu/vc/commit/e1ea46f3d3bd5e1393e1686af6d9c465efd1d4ca

**Comment by masv3971** [comment]
Can't find id/mapping in the code, but https://github.com/dc4eu/vc/blob/masv_api-2.8/internal/apigw/httpserver/service.go#L93
