### ISSUE TITLE
Missing request parameter validation in /notification endpoint

### ISSUE THREAD

**Issue by JuAlMan** [dc4eu/vc#85]
Using image docker.sunet.se/dc4eu/apigw:apiv28

There seems to be no validation of the required request parameters for this endpoint, leaving out any of them does not yield a validation error. You just get an error that no results have been found.

**Comment by masv3971** [comment]
Is related to https://github.com/dc4eu/vc/commit/e1ea46f3d3bd5e1393e1686af6d9c465efd1d4ca and should be fixed.
