### ISSUE TITLE
Swagger Docs: Make API version info consistent with implemented spec version

### ISSUE THREAD

**Issue by JuAlMan** [dc4eu/vc#88]
Currently the swagger docs contain the following version info:
```
info:
  contact: {}
  title: Datastore API
  version: 0.1.0
```
In our opinion this version should be consistent with the implemented spec version which is currently 2.8(.0)

**Comment by masv3971** [comment]
https://github.com/dc4eu/vc/commit/8051a1df108f6a61e4479f7b227071b3ea26eb7c
