### ISSUE TITLE
/credential should take additional input

### ISSUE THREAD

**Issue by fabienpe** [dc4eu/vc#99]
If there are several documents of the same type (e.g., 2 PDA1), at one authentic source, for the same person (same `authentic_source_person_id`), a POST to `/credential` returns nevertheless an SD-JWT credential but we don't know for which of the documents.

**Comment by masv3971** [comment]
Hello,

this should have been solved in the latest release, `0.4.5`. Please try it out.

**Comment by fabienpe** [comment]
Looks like it. Thanks.
